# Travis
language: node_js

node_js:
  - 0.10.30
    
before_script:
 # - npm link
 # - mkdir -p shippable/codecoverage

after_success:
  - echo $TOTO
  - git remote -v
  - git config --global user.email "pim3352@g.rit.edu"
  - git config --global user.name "pavelmora26"
 - git checkout master
 - npm version patch
  - git commit -am "[skip ci] bump version"
 - git log --oneline
  - git remote set-url origin https://github.com/pavelmora26/Travis.git
  - git push origin master
#  - npm run coverage
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - mocha test -R mocha-lcov-reporter  && 
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
